version: '3'
services:
  app:
    build: .
    env_file:
      - ./app.env
    container_name: first_golang_app
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - learning
  
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - '5432:5432'
    volumes:
      - postgresDB:/var/lib/postgresql/data
    env_file:
      - ./app.env
    networks:
      - learning

networks:
  learning:
    driver: bridge

volumes:
  postgresDB:
    driver: local